### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ghost** [afrase/mysqldumpsplit#3]
I was trying to split a 19GB mysql dump file which has 920 tables.

I installed via homebrew
version = 0.1.0

```
mysqldumpsplit -i mysqldump.sql -o splitted/
2018/03/01 17:04:01 outputing all tables to splitted/
2018/03/01 17:04:01 begin processing mysqldump.sql
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x10af637]

goroutine 17 [running]:
compress/gzip.(*Reader).Read(0x0, 0xc4200c8000, 0x2000, 0x2000, 0x1, 0x101650100000000, 0x0)
	/usr/local/go/src/compress/gzip/gunzip.go:247 +0x37
bufio.(*Reader).fill(0xc420058120)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc420058120, 0xc42004a20a, 0xc4200c8000, 0xc420046f40, 0x10b35db, 0x10c8fc0, 0x2000)
	/usr/local/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc420058120, 0x116a20a, 0xc42000c030, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:416 +0x6b
bufio.(*Reader).ReadString(0xc420058120, 0xc42005810a, 0x3, 0xc420018090, 0x22, 0x0)
	/usr/local/go/src/bufio/bufio.go:456 +0x38
github.com/afrase/mysqldumpsplit/msds.LineReader(0xc42000c030, 0xc420076060, 0xc4200760c0, 0xc420076240, 0xc4200761e0, 0xc420076180, 0xc420076120)
	/go/src/github.com/afrase/mysqldumpsplit/msds/mysqldumpsplit.go:49 +0x47
created by main.main
	/go/src/github.com/afrase/mysqldumpsplit/main.go:86 +0x4a5
```

**Comment by afrase** [comment]
It looks like it's having a problem reading the gziped file.

Try renaming `mysqldump.sql` to `mysqldump.sql.gz` then extract the file and run `mysqldumpsplit` against the extracted SQL dump.

**Comment by ghost** [comment]
Hi @afrase 

Renaming to .gz didn't work. It gives following output

```
$ mysqldumpsplit -i mysqldump.sql.gz -o out/
2018/03/01 20:23:42 outputing all tables to out/
2018/03/01 20:23:42 begin processing mysqldump.sql.gz
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x10af637]

goroutine 6 [running]:
compress/gzip.(*Reader).Read(0x0, 0xc4200c4000, 0x2000, 0x2000, 0x1, 0x101650100000000, 0x0)
	/usr/local/go/src/compress/gzip/gunzip.go:247 +0x37
bufio.(*Reader).fill(0xc4200a4060)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc4200a4060, 0xc42004a20a, 0xc4200c4000, 0xc4200baf40, 0x10b35db, 0x10c8fc0, 0x2000)
	/usr/local/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc4200a4060, 0x116a20a, 0xc42000c030, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:416 +0x6b
bufio.(*Reader).ReadString(0xc4200a4060, 0xc4200a400a, 0x3, 0xc420012100, 0x1d, 0x0)
	/usr/local/go/src/bufio/bufio.go:456 +0x38
github.com/afrase/mysqldumpsplit/msds.LineReader(0xc42000c030, 0xc420076060, 0xc4200760c0, 0xc420076240, 0xc4200761e0, 0xc420076180, 0xc420076120)
	/go/src/github.com/afrase/mysqldumpsplit/msds/mysqldumpsplit.go:49 +0x47
created by main.main
	/go/src/github.com/afrase/mysqldumpsplit/main.go:86 +0x4a5
```

Then I tried compress to `gz`. Then it gives following output.

```
$ mysqldumpsplit -i mysqldump.sql.gz -o tmp/
2018/03/01 20:48:11 outputing all tables to tmp/
2018/03/01 20:48:11 begin processing mysqldump.sql.gz
2018/03/01 20:48:11 extracting table: activity
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.main()
	/go/src/github.com/afrase/mysqldumpsplit/main.go:91 +0x592

goroutine 5 [chan receive]:
github.com/afrase/mysqldumpsplit/msds.Logger(0xc420076060, 0xc4200760c0, 0xc420076240, 0xc4200761e0, 0xc420076180, 0xc420076120)
	/go/src/github.com/afrase/mysqldumpsplit/msds/mysqldumpsplit.go:207 +0x57
created by main.main
	/go/src/github.com/afrase/mysqldumpsplit/main.go:73 +0x281

goroutine 6 [chan send]:
github.com/afrase/mysqldumpsplit/msds.LineReader(0xc42000c030, 0xc420076060, 0xc4200760c0, 0xc420076240, 0xc4200761e0, 0xc420076180, 0xc420076120)
	/go/src/github.com/afrase/mysqldumpsplit/msds/mysqldumpsplit.go:50 +0x7a
created by main.main
	/go/src/github.com/afrase/mysqldumpsplit/main.go:86 +0x4a5

goroutine 7 [chan send]:
github.com/afrase/mysqldumpsplit/msds.LineParser(0xc420076060, 0xc4200760c0, 0xc420076240, 0xc4200761e0, 0xc420076180, 0xc420076120, 0xc420076100)
	/go/src/github.com/afrase/mysqldumpsplit/msds/mysqldumpsplit.go:69 +0x2c5
created by main.main
	/go/src/github.com/afrase/mysqldumpsplit/main.go:87 +0x4f0

goroutine 8 [chan receive]:
github.com/afrase/mysqldumpsplit/msds.Writer(0x7ffeefbffbc6, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420076060, 0xc4200760c0, ...)
	/go/src/github.com/afrase/mysqldumpsplit/msds/mysqldumpsplit.go:146 +0x1d2
created by main.main
	/go/src/github.com/afrase/mysqldumpsplit/main.go:88 +0x578
```
