### ISSUE TITLE
segmentation fault on mac m1

### ISSUE THREAD

**Issue by kyhite** [afrase/mysqldumpsplit#5]
segmentation fault on mac m1. 
```

  >> mysqldumpsplit -i "sqlFile.sql" -o "./outputFolderPath"
 >> zsh: segmentation fault  mysqldumpsplit -i  -o
```
downloaded straight from homebrew. os = Ventura 13.0.1.

**Comment by miloskroulik** [comment]
It looks similar on Linux x64:

```
2024/01/30 17:44:00 outputing all tables to ./db
2024/01/30 17:44:00 begin processing myfile.sql
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x4af8f7]

goroutine 20 [running]:
compress/gzip.(*Reader).Read(0x0, 0xc4200da000, 0x2000, 0x2000, 0x1, 0x101650100000000, 0x0)
	/usr/local/go/src/compress/gzip/gunzip.go:247 +0x37
bufio.(*Reader).fill(0xc4200d6060)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc4200d6060, 0xc42008420a, 0xc4200da000, 0xc4200cbf40, 0x4b389b, 0x4c9d60, 0x2000)
	/usr/local/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc4200d6060, 0x56b20a, 0xc420092020, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:416 +0x6b
bufio.(*Reader).ReadString(0xc4200d6060, 0xc4200d600a, 0x3, 0xc4200b0060, 0x1d, 0x0)
	/usr/local/go/src/bufio/bufio.go:456 +0x38
github.com/afrase/mysqldumpsplit/msds.LineReader(0xc420092020, 0xc420082060, 0xc4200820c0, 0xc420082240, 0xc4200821e0, 0xc420082180, 0xc420082120)
	/go/src/github.com/afrase/mysqldumpsplit/msds/mysqldumpsplit.go:49 +0x47
created by main.main
	/go/src/github.com/afrase/mysqldumpsplit/main.go:86 +0x4a5
```
